### ISSUE TITLE
Programar codigo de Ant Colony 

### ISSUE THREAD

**Issue by santibatte** [optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-ltejadal#8]

**Comment by C1587S** [comment]
Al respecto se hicieron los siguientes cambios:

- Se incluyó el _script_ del algoritmo en la ruta `practica-1-segunda-parte-ltejadal/src/ant_colony/aco_tsp.py`
- Se incluyó el archivo `requirements.txt` en la raíz del repositorio.
- Se ajustó `practica-1-segunda-parte-ltejadal/src/setup.py` para una correcta instalación de la librería.
- Se incluyeron los _notebooks_:
    - `implementacion_ejemplo.ipynb`: ejemplifia el uso de la librería con tres _datasets_.
    -  `preliminares.ipynb`: Muestra la construcción gradual de las funciones utilizadas en la librería.
